server:
  port: 8079
spring:
  application:
    name: SpringCloudGateway
#jwt:
#  secret: y8GMepxPjRQ2vD+GjZZmPwfvMqlxeGwK/b9lqvWGtoR+z1p85a1Y2zkFtdMpvyS40hUauzTvJiE6Hs4dEAheaw==
#  expiration: 86400  # 24小时