server:
  port: 8084 # 指定服务端口，如果不指定默认就是8080

spring:
  application:
    name: order-service # 指定服务名称，项目启动后注册到nacos的名称就是这个
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_service?useSSL=false
    username: "root"
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      password: "ABSESP040113"





mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: ynu.edu.order_service.po

logging:
  level:
    com.baomidou: DEBUG
    org.apache.ibatis: DEBUG
debug: true
